-keep class com.smartvision.ai.domain.models.** { *; }
-keep class com.google.mlkit.** { *; }
-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }
-keep class com.google.ai.client.** { *; }
-keep class dagger.hilt.** { *; }
-keep @dagger.hilt.android.HiltAndroidApp class * { *; }
-keepclasseswithmembers class * { @dagger.hilt.android.lifecycle.HiltViewModel <init>(...); }
-dontwarn org.tensorflow.**
-dontwarn com.google.ai.client.**
